#!/usr/bin/env node
'use strict';
const fs = require("fs");
const path = require('path');
const child_process = require("child_process");
const rootDir = path.resolve(__dirname, '..');
const SERVER_PATH = path.resolve(rootDir, '../pokemon-showdown');
process.chdir(rootDir);
if (!fs.existsSync(SERVER_PATH)) { throw new Error(`Local pokemon-showdown server not found.\nExpected at: ${SERVER_PATH}`); }
const buildStartTime = Date.now();
process.stdout.write("Using local pokemon-showdown server... ");
const serverBuildStartTime = Date.now();
child_process.execSync('npm run build', {
  cwd: SERVER_PATH,
  stdio: 'inherit',
});
console.log(`DONE (server build took ${((Date.now() - serverBuildStartTime) / 1000).toFixed(1)}s)`);
const Dex = require(path.join(SERVER_PATH, 'dist/sim/dex')).Dex;
const CompoundWordNames =
require(path.join(SERVER_PATH, 'dist/data/aliases')).CompoundWordNames;
const toID = Dex.toID;
process.stdout.write("Loading gen 6 data... ");
Dex.includeData();
console.log("DONE");
function es3stringify(obj) {
	if (!obj) return 'null';
	const buf = JSON.stringify(obj);
	if (!buf) return 'null';
	return buf.replace(
    /"([A-Za-z][A-Za-z0-9]*)":/g,
    (fullMatch, key) =>
    (['return', 'new', 'delete'].includes(key) ? fullMatch : `${key}:`)
  );
}
function requireNoCache(...args) {
  const pathSpec = args.length === 1 ? args[0] : path.join(args[0], args[1]);
  delete require.cache[require.resolve(pathSpec)];
  return require(pathSpec);
}
//region Overlay helpers
const CLIENT_DATA_DIR = path.join(rootDir, 'play.pokemonshowdown.com', 'data');
const MOD_ID = 'gen9indigostarstorm';
function ensureDir(dir) { fs.mkdirSync(dir, {recursive: true}); }
function pickExport(mod, keys) {
	for (const k of keys) { if (mod && mod[k] && typeof mod[k] === 'object') return mod[k]; }
	return null;
}
function requireServer(relPath) { return requireNoCache(path.join(SERVER_PATH, relPath)) }
function writeBattleExport(outPath, exportName, data) {
	if (!data || typeof data !== 'object') { throw new Error(`Refusing to write ${outPath}: export ${exportName} is not an object`); }
	const buf = `exports.${exportName} = ` + es3stringify(data) + ';';
	if (!buf || buf.includes('undefined')) { throw new Error(`Serialization failed for ${outPath} (${exportName})`); }
	ensureDir(path.dirname(outPath));
	fs.writeFileSync(outPath, buf);
}
function cloneObjTable(src) {
  const out = {};
  for (const id in src) out[id] = {...src[id]};
  return out;
}
// Load item text descriptions
process.stdout.write("Loading item text descriptions... ");
const ItemsText = requireNoCache(path.join(SERVER_PATH,'dist/data/text/items.js')).ItemsText;
// Merge shortDesc from ItemsText into Dex.data.Items
for (const id in ItemsText) { if (Dex.data.Items[id] && ItemsText[id].shortDesc) { Dex.data.Items[id].shortDesc = ItemsText[id].shortDesc; } }
console.log("DONE");
console.log(`Merged descriptions for ${Object.keys(ItemsText).length} items`);
//region Build search-index.js
{
	process.stdout.write("Building `data/search-index.js`... ");
	let index = [];
	index = index.concat(Object.keys(Dex.data.Pokedex).map(x => x + ' pokemon'));
	index = index.concat(Object.keys(Dex.data.Moves).map(x => x + ' move'));
	index = index.concat(Object.keys(Dex.data.Items).map(x => x + ' item'));
	index = index.concat(Object.keys(Dex.data.Abilities).map(x => x + ' ability'));
	index = index.concat(Object.keys(Dex.data.TypeChart).map(x => toID(x) + ' type'));
	index = index.concat(['physical', 'special', 'status'].map(x => toID(x) + ' category'));
	const moveFlagIds = new Set();
	for (const id in Dex.data.Moves) { for (const flagId in (Dex.data.Moves[id].flags || {})) { moveFlagIds.add(flagId); } }
	const speciesTagIds = new Set();
	for (const id in Dex.data.Pokedex) { for (const tag of (Dex.data.Pokedex[id].tags || [])) { speciesTagIds.add(toID(tag)); } }
	index = index.concat([...moveFlagIds, ...speciesTagIds].map(x => x + ' flag'));
	const guardActionMoveIds = new Set();
	for (const id in Dex.data.Moves) { if (Dex.data.Moves[id].guardActionCD) guardActionMoveIds.add(id); }
	index = index.concat([...guardActionMoveIds].map(x => x + ' guardaction'));
	index = index.concat(['monster', 'water1', 'bug', 'flying', 'field', 'fairy', 'grass', 'humanlike', 'water3', 'mineral', 'amorphous', 'water2', 'ditto', 'dragon', 'undiscovered',].map(x => toID(x) + ' egggroup'));
	index = index.concat(['ou', 'uu', 'ru', 'nu', 'pu', 'zu', 'lc', 'nfe', 'uber', 'uubl', 'rubl', 'nubl', 'publ', 'zubl', 'cap', 'caplc', 'capnfe',].map(x => toID(x) + ' tier'));
	index = index.concat([ 'fragile', 'volatile', 'pokeball', 'megastone', 'zcrystals', 'tradeevo', 'evostones', 'evolution', 'berry', 'consumable', 'species', 'typeplates', 'healing', 'statboost', 'statuscure', 'resist', 'reactive', 'utility', 'weather', 'terrain',
	].map(x => toID(x) + ' itemclass'));
	const BattleArticleTitles = {};
	try {
		for (const file of fs.readdirSync('../dex.pokemonshowdown.com/articles/')) {
			if (file.endsWith('.md')) {
				const id = file.slice(0, -3);
				const contents = '' + fs.readFileSync('../dex.pokemonshowdown.com/articles/' + file);
				if (contents.startsWith('# ')) {
					const title = contents.slice(2, contents.indexOf('\n'));
					if (title !== id.charAt(0).toUpperCase() + id.slice(1)) { BattleArticleTitles[id] = title; }
				}
				index.push('' + id + ' article');
			}
		}
	} catch { console.log('\n(WARNING: NO ARTICLES)'); }
	index.push('pokemon article');
	index.push('moves article');
	const compoundTable = new Map(CompoundWordNames.map(word => [toID(word), word]));
	// generate aliases
	function generateAlias(id, name, type) {
		name = compoundTable.get(id) || name;
		if (type === 'pokemon' && !compoundTable.has(id)) {
			const species = Dex.species.get(id);
			const baseid = toID(species.baseSpecies);
			if (baseid !== id) { name = (compoundTable.get(baseid) || species.baseSpecies) + ' ' + species.forme; }
		}
		if (name.endsWith(' Mega-X') || name.endsWith(' Mega-Y')|| name.endsWith(' Mega-Z')) {
			index.push('mega' + toID(name.slice(0, -7) + name.slice(-1)) + ' ' + type + ' ' + id + ' 0');
			index.push('m' + toID(name.slice(0, -7) + name.slice(-1)) + ' ' + type + ' ' + id + ' 0');
			index.push('mega' + toID(name.slice(-1)) + ' ' + type + ' ' + id + ' ' + toID(name.slice(0, -7)).length);
		} else if (name.endsWith(' Mega')) {
			index.push('mega' + toID(name.slice(0, -5)) + ' ' + type + ' ' + id + ' 0');
			index.push('m' + toID(name.slice(0, -5)) + ' ' + type + ' ' + id + ' 0');
		} else if (name.endsWith(' Alola')) { index.push('alolan' + toID(name.slice(0, -6)) + ' ' + type + ' ' + id + ' 0'); } 
		else if (name.endsWith(' Galar')) { index.push('galarian' + toID(name.slice(0, -6)) + ' ' + type + ' ' + id + ' 0'); } 
		else if (name.endsWith(' Hisui')) { index.push('hisuian' + toID(name.slice(0, -6)) + ' ' + type + ' ' + id + ' 0'); }
		const fullSplit = name.split(/ |-/).map(toID);
		if (fullSplit.length < 2) return;
		const fullAcronym = fullSplit.map(x => x.charAt(0)).join('') + fullSplit.at(-1).slice(1);
		index.push('' + fullAcronym + ' ' + type + ' ' + id + ' 0');
		for (let i = 1; i < fullSplit.length; i++) { index.push('' + fullSplit.slice(i).join('') + ' ' + type + ' ' + id + ' ' + fullSplit.slice(0, i).join('').length); }
		const spaceSplit = name.split(' ').map(toID);
		if (spaceSplit.length !== fullSplit.length) {
			const spaceAcronym = spaceSplit.map(x => x.charAt(0)).join('') + spaceSplit.at(-1).slice(1);
			if (spaceAcronym !== fullAcronym) { index.push('' + spaceAcronym + ' ' + type + ' ' + id + ' 0'); }
		}
	}
	for (const id in Dex.data.Pokedex) {
		const name = Dex.data.Pokedex[id].name;
		if (Dex.data.Pokedex[id].isCosmeticForme) continue;
		generateAlias(id, name, 'pokemon');
	}
	for (const id in Dex.data.Moves) {
		const move = Dex.data.Moves[id];
		const name = move.name;
		generateAlias(id, name, 'move');
	}
	let fragileCount = 0;
	let volatileCount = 0;
	let pokeballCount = 0;
	let consumableCount = 0;
	let evolutionCount = 0;
	let tradeEvoCount = 0;
	for (const id in Dex.data.Items) {
		const name = Dex.data.Items[id].name;
		generateAlias(id, name, 'item');
		// Add item classification tags for searchability
		const item = Dex.data.Items[id];
		const desc = item.shortDesc || item.desc || '';
		if (item.isFragile) {
			fragileCount++;
			if (fragileCount <= 3) console.log(`  Tagged fragile: ${id}`);
		} else if (item.isMildlyFragile) {
			volatileCount++;
			if (volatileCount <= 3) console.log(`  Tagged volatile: ${id}`);
		}
		// Consumable/Pokeball/Evolution/Trade Evo classification
		const evolutionStones = ['dawnstone', 'duskstone', 'firestone', 'icestone', 'leafstone', 'moonstone', 'shinystone', 'sunstone', 'thunderstone', 'waterstone'];
		const isEvolutionStone = evolutionStones.includes(id);
		const isEvolution = desc.includes('Evolves') || isEvolutionStone;
		const isTradeEvo = desc.includes('when traded');
		const isSingleUse = desc.includes('Single use');
		if (item.isPokeball) {
			pokeballCount++;
			if (pokeballCount <= 3) console.log(`  Tagged pokeball: ${id}`);
		} else if (isTradeEvo) {
			tradeEvoCount++;
			if (tradeEvoCount <= 3) console.log(`  Tagged tradeevo: ${id}`);
		} else if (isEvolution) {
			evolutionCount++;
			if (evolutionCount <= 3) console.log(`  Tagged evolution: ${id}`);
		} else if (item.isBerry || item.isGem || isSingleUse) {
			consumableCount++;
			if (consumableCount <= 3) console.log(`  Tagged consumable: ${id}`);
		}
	}
	console.log(`Itemclass totals: fragile=${fragileCount}, volatile=${volatileCount}, pokeball=${pokeballCount}, consumable=${consumableCount}, evolution=${evolutionCount}, tradeevo=${tradeEvoCount}`);
	for (const id in Dex.data.Abilities) {
		const name = Dex.data.Abilities[id].name;
		generateAlias(id, name, 'ability');
	}
	// hardcode ultra beasts
	const ultraBeasts = {
		ub01symbiont: "nihilego",
		ub02absorption: "buzzwole",
		ub02beauty: "pheromosa",
		ub03lightning: "xurkitree",
		ub04blade: "kartana",
		ub04blaster: "celesteela",
		ub05glutton: "guzzlord",
		ubburst: "blacephalon",
		ubassembly: "stakataka",
		ubadhesive: "poipole",
		ubstinger: "naganadel",
	};
	for (const [ubCode, id] of Object.entries(ultraBeasts)) { index.push(`${ubCode} pokemon ${id} 0`); }
	index.sort();
	// manually rearrange
	index[index.indexOf('grass type')] = 'grass egggroup';
	index[index.indexOf('grass egggroup')] = 'grass type';
	index[index.indexOf('fairy type')] = 'fairy egggroup';
	index[index.indexOf('fairy egggroup')] = 'fairy type';
	index[index.indexOf('flying type')] = 'flying egggroup';
	index[index.indexOf('flying egggroup')] = 'flying type';
	index[index.indexOf('dragon type')] = 'dragon egggroup';
	index[index.indexOf('dragon egggroup')] = 'dragon type';
	index[index.indexOf('bug type')] = 'bug egggroup';
	index[index.indexOf('bug egggroup')] = 'bug type';
	index[index.indexOf('psychic type')] = 'psychic move';
	index[index.indexOf('psychic move')] = 'psychic type';
	index[index.indexOf('ditto pokemon')] = 'ditto egggroup';
	index[index.indexOf('ditto egggroup')] = 'ditto pokemon';
	const BattleSearchIndex = index.map(x => {
		x = x.split(' ');
		if (x.length > 3) {
			x[3] = Number(x[3]);
			x[2] = index.indexOf(x[2] + ' ' + x[1]);
		}
		return x;
	});
	const BattleSearchIndexOffset = BattleSearchIndex.map(entry => {
		const id = entry[0];
		let name = '';
		switch (entry[1]) {
		case 'pokemon': name = Dex.species.get(id).name; break;
		case 'move': name = Dex.moves.get(id).name; break;
		case 'item': name = Dex.items.get(id).name; break;
		case 'ability': name = Dex.abilities.get(id).name; break;
		case 'article': name = BattleArticleTitles[id] || ''; break;
		case 'itemclass': name = id; break;
		}
		let res = '';
		let nonAlnum = 0;
		for (let i = 0, j = 0; i < id.length; i++, j++) {
			while (!/[a-zA-Z0-9]/.test(name[j])) {
				j++;
				nonAlnum++;
			}
			res += nonAlnum;
		}
		if (nonAlnum) return res;
		return '';
	});
	const BattleSearchCountIndex = {};
	for (const type in Dex.data.TypeChart) {
		BattleSearchCountIndex[type + ' move'] = Object.keys(Dex.data.Moves)
			.filter(id => (Dex.data.Moves[id].type === type)).length;
	}
	for (const type in Dex.data.TypeChart) {
		BattleSearchCountIndex[type + ' pokemon'] = Object.keys(Dex.data.Pokedex)
			.filter(id => ( !Dex.data.Pokedex[id].isCosmeticForme && Dex.data.Pokedex[id].types.indexOf(type) >= 0 )).length;
	}
	let buf = '// DO NOT EDIT - automatically built with build-tools/build-indexes\n\n';
	buf += 'exports.BattleSearchIndex = ' + JSON.stringify(BattleSearchIndex) + ';\n\n';
	buf += 'exports.BattleSearchIndexOffset = ' + JSON.stringify(BattleSearchIndexOffset) + ';\n\n';
	buf += 'exports.BattleSearchCountIndex = ' + JSON.stringify(BattleSearchCountIndex) + ';\n\n';
	buf += 'exports.BattleArticleTitles = ' + JSON.stringify(BattleArticleTitles) + ';\n\n';
	fs.writeFileSync('play.pokemonshowdown.com/data/search-index.js', buf);
}
console.log("DONE");
//region Build teambuilder-tables.js
process.stdout.write("Building `data/teambuilder-tables.js`... ");
{
	const BattleTeambuilderTable = {};
	let buf = '// DO NOT EDIT - automatically built with build-tools/build-indexes\n\n';
	const MODS = ['gen9indigostarstorm'];
	const GENS = [9, 8, 7, 6, 5, 4, 3, 2, 1];
	const DOUBLES = GENS.filter(x => x > 2).map(num => -num);
	const VGC = GENS.filter(x => x > 3).map(num => -num - 0.5);
	const NFE = GENS.map(num => num + 0.3);
	const LC = GENS.map(num => num + 0.7);
	const STADIUM = [2.04, 1.04];
	const NATDEX = [9.1, 8.1];
	const OTHER = [9.9, 9.6, 9.4, 9.2, -9.4, 8.6, 8.4, 8.2, 8.1, -8.4, -8.6, 7.1, 5.1, 3.1];
	// process.stdout.write("\n  ");
	for (const genIdent of [...GENS, ...DOUBLES, ...VGC, ...NFE, ...STADIUM, ...OTHER, ...NATDEX, ...LC]) {
		const isMetBattle = ('' + genIdent).endsWith('.2');
		const isNFE = ('' + genIdent).endsWith('.3');
		const isLC = ('' + genIdent).endsWith('.7');
		const isNatDex = ('' + genIdent).endsWith('.1') && genIdent > 8;
		const isDoubles = (genIdent < 0);
		const isVGC = ('' + genIdent).endsWith('.5');
		const isGen9BH = genIdent === 9.9;
		const genNum = Math.floor(isDoubles ? -genIdent : genIdent);
		const gen = (() => {
			let genStr = 'gen' + genNum;
			return genStr;
		})();
		// process.stdout.write("" + gen + (isDoubles ? " doubles" : "") + "... ");
		// Check if mod exists before processing
		try { Dex.mod(gen); } 
		catch (e) { continue; } // Mod doesn't exist, skip
		const pokemon = Object.keys(Dex.data.Pokedex);
		pokemon.sort();
		const tierTable = {};
		const overrideTier = {};
		const ndDoublesBans = {};
		const thirtyfivePokes = {};
		const monotypeBans = {};
		const nonstandardMoves = [];
		for (const id of pokemon) {
			const species = Dex.mod(gen).species.get(id);
			const baseSpecies = Dex.mod(gen).species.get(species.baseSpecies);
			if (species.gen > genNum) continue;
			// Hard-hide CAP and MissingNo/Glitch Pokémon from teambuilder lists
			if (species.isNonstandard === 'CAP') continue;
			if (species.num === 0) continue;
			const speciesTier = (() => {
				if (isMetBattle) {
					let tier = species.tier;
					if (species.isNonstandard) {
						if (species.isNonstandard === 'Past') {
							try { tier = Dex.mod('gen7').species.get(species.name).tier; } 
							catch (e) { tier = 'OU'; }
						} 
						else { tier = 'OU'; }
					}
					if (species.isNonstandard === 'Gigantamax') tier = '(Uber)';
					const format = Dex.formats.get(gen + 'metronomebattle');
					let bst = 0;
					for (const stat of Object.values(species.baseStats)) { bst += stat; }
					if (bst > 625) tier = 'Illegal';
					if (Dex.formats.getRuleTable(format).isBannedSpecies(species)) tier = 'Illegal';
					if (species.types.includes('Steel')) tier = 'Illegal';
					return tier;
				}
				if (isNFE) {
					let tier = species.tier;
					if (!species.nfe) tier = 'Illegal';
					const format = Dex.formats.get(gen + 'nfe');
					const banlist = Dex.formats.getRuleTable(format);
					if (banlist.isBannedSpecies(species)) { tier = 'Uber'; }
					return tier;
				}
				if (isLC) {
					let tier = species.tier;
					const lc = Dex.formats.get(gen + 'lc');
					const lcBanlist = Dex.formats.getRuleTable(lc);
					const prevoSpecies = Dex.mod(gen).species.get(species.prevo);
					if (!species.nfe || (prevoSpecies.exists && prevoSpecies.gen <= genNum) || lcBanlist.isBannedSpecies(species)) { tier = 'Illegal'; }
					if (/^([OURNPZ]U(BL)?|Uber|AG)$/g.test(tier) && tier !== 'Illegal') { tier = 'LC'; }
					return tier;
				}
				if (isVGC) {
					if (species.isNonstandard && species.isNonstandard !== 'Gigantamax') return 'Illegal';
					if (baseSpecies.tags.includes('Mythical')) return 'Mythical';
					if (baseSpecies.tags.includes('Restricted Legendary')) return 'Restricted Legendary';
					if (species.tier === 'NFE') return 'NFE';
					if (species.tier === 'LC') return 'LC';
					return 'Regular';
				}
				if (isGen9BH) {
					if ((species.natDexTier === 'Illegal' || species.forme.includes('Totem')) && !['Floette-Eternal', 'Greninja-Ash', 'Xerneas-Neutral'].includes(species.name)) { return 'Illegal'; }
					if ((species.name === 'Xerneas' || species.battleOnly || species.forme === 'Eternamax') && !(species.isPrimal || ['Greninja-Ash', 'Necrozma-Ultra'].includes(species.name))) { return 'Illegal'; }
					if (species.isNonstandard && ['LGPE', 'CAP', 'Future'].includes(species.isNonstandard)) return 'Illegal';
					return species.tags.includes('Mythical') ? 'Mythical' :
						species.tags.includes('Legendary') ? 'Legendary' :
						species.tags.includes('Paradox') ? 'Paradox' :
						species.tags.includes('Restricted Legendary') ? 'Restricted Legendary' :
						species.tags.includes('Restricted Mythical') ? 'Restricted Mythical' :
						species.tags.includes('Restricted Paradox') ? 'Restricted Paradox' :
						species.tags.includes('Mega') ? 'Mega' :
						species.nfe ? (species.prevo ? 'NFE' : 'LC') : 'Regular';
				}
				if (isDoubles && genNum > 4) { return species.doublesTier; }
				return species.tier;
			})();
			overrideTier[species.id] = speciesTier;
			if (species.forme) { if (['Aegislash', 'Castform', 'Cherrim', 'Cramorant', 'Eiscue', 'Meloetta', 'Mimikyu', 'Minior', 'Morpeko', 'Ramnarok', 'Wishiwashi',].includes(species.baseSpecies) || species.forme.includes('Totem') || species.forme.includes('Zen') || (species.baseSpecies === 'Ogerpon' && species.forme.includes('Tera')) || species.isCosmeticForme)  { continue; } }
			if (!tierTable[speciesTier]) tierTable[speciesTier] = [];
			tierTable[speciesTier].push(id);
			if (genNum === 9) {
				const ubersUU = Dex.formats.get(gen + 'ubersuu');
				if (ubersUU.exists && Dex.formats.getRuleTable(ubersUU).isBannedSpecies(species)) { ubersUUBans[species.id] = 1; }
				const nd35Pokes = Dex.formats.get(gen + 'nationaldex35pokes');
				if (nd35Pokes.exists && !Dex.formats.getRuleTable(nd35Pokes).isBannedSpecies(species)) { thirtyfivePokes[species.id] = 1; }
			}
		}
		// NOTE: nonstandardMoves logic removed here (it referenced undefined bMove/move).
		// Keep nonstandardMoves as [] unless you implement it properly later.
		const tiers = [];
		const items = [];
		const formatSlices = {};
		if (isNFE) {
			BattleTeambuilderTable[gen + 'nfe'] = {};
			BattleTeambuilderTable[gen + 'nfe'].tiers = tiers;
			BattleTeambuilderTable[gen + 'nfe'].overrideTier = overrideTier;
			BattleTeambuilderTable[gen + 'nfe'].formatSlices = formatSlices;
		} else if (isLC) {
			BattleTeambuilderTable[gen + 'lc'] = {};
			BattleTeambuilderTable[gen + 'lc'].tiers = tiers;
			BattleTeambuilderTable[gen + 'lc'].overrideTier = overrideTier;
			BattleTeambuilderTable[gen + 'lc'].formatSlices = formatSlices;
		} else if (isVGC) {
			BattleTeambuilderTable[gen + 'vgc'] = {};
			BattleTeambuilderTable[gen + 'vgc'].tiers = tiers;
			BattleTeambuilderTable[gen + 'vgc'].formatSlices = formatSlices;
		} else if (isDoubles) {
			BattleTeambuilderTable[gen + 'doubles'] = {};
			BattleTeambuilderTable[gen + 'doubles'].tiers = tiers;
			BattleTeambuilderTable[gen + 'doubles'].items = items;
			BattleTeambuilderTable[gen + 'doubles'].overrideTier = overrideTier;
			BattleTeambuilderTable[gen + 'doubles'].formatSlices = formatSlices;
		} else if (isGen9BH) {
			BattleTeambuilderTable['bh'] = {};
			BattleTeambuilderTable['bh'].tiers = tiers;
			BattleTeambuilderTable['bh'].overrideTier = overrideTier;
			BattleTeambuilderTable['bh'].formatSlices = formatSlices;
		} else if (gen === 'gen9') {
			BattleTeambuilderTable.tiers = tiers;
			BattleTeambuilderTable.items = items;
			BattleTeambuilderTable.overrideTier = overrideTier;
			BattleTeambuilderTable.monotypeBans = monotypeBans;
			BattleTeambuilderTable.formatSlices = formatSlices;
			BattleTeambuilderTable.learnsets = {}; // Initialize learnsets for gen 9
		} else {
			BattleTeambuilderTable[gen] = {};
			if (genNum === 5) { BattleTeambuilderTable[gen].gen5zuBans = gen5zuBans; }
			if (genNum === 4) { BattleTeambuilderTable[gen].gen4puBans = gen4puBans; }
			BattleTeambuilderTable[gen].overrideTier = overrideTier;
			BattleTeambuilderTable[gen].tiers = tiers;
			BattleTeambuilderTable[gen].items = items;
			BattleTeambuilderTable[gen].formatSlices = formatSlices;
			if (genNum >= 5) { BattleTeambuilderTable[gen].monotypeBans = monotypeBans; }
		}
		const tierOrder = (() => {
			if (isVGC || isGen9BH) { return ["Mythical", "Restricted Legendary", "Regular", "NFE", "LC"]; }
			if (isDoubles && genNum > 4) { return ["DUber", "(DUber)", "DOU", "DBL", "(DOU)", "DUU", "(DUU)", "New", "NFE", "LC"]; }
			if (gen === 'gen4') { return ["AG", "Uber", "OU", "(OU)", "UUBL", "UU", "NUBL", "NU", "NFE", "LC"]; }
			return [ "AG", "Uber", "(Uber)", "OU", "(OU)", "UUBL", "UU", "RUBL", "RU", "NUBL", "NU", "PUBL", "PU", "ZUBL", "ZU", "New", "NFE", "LC", "Unreleased" ];		})();
		for (const tier of tierOrder) {
			if (tier in {
				OU: 1, UUBL: 1, AG: 1, Uber: 1, UU: 1, RU: 1, NU: 1, PU: 1, ZU: 1, NFE: 1, LC: 1, DOU: 1, DUU: 1,
				"(DUU)": 1, New: 1, Legal: 1, Regular: 1, "Restricted Legendary": 1,
			}) {
				let usedTier = tier;
				if (usedTier === "(DUU)") usedTier = "DNU";
				formatSlices[usedTier] = tiers.length;
			}
			if (!tierTable[tier]) continue;
			if (tier === "(PU)") { tiers.push(['header', "Below PU"]); } 
			else if (tier === "(DUU)") { tiers.push(['header', "Below DUU"]); } 
			else if (tier.charAt(0) === '(') { tiers.push(['header', tier.slice(1, -1) + " by technicality"]); } 
			else if (tier === "NFE") { tiers.push(['header', "NFEs not in a higher tier"]); } 
			else { tiers.push(['header', tier]); }
			tiers.push(...tierTable[tier]);
		}
		if (!isDoubles) {
			if (!formatSlices['OU']) formatSlices['OU'] = formatSlices['New'];
			if (!formatSlices['UU']) formatSlices['UU'] = formatSlices['New'];
			if (!formatSlices['RU']) formatSlices['RU'] = formatSlices['New'];
		} else {
			if (!formatSlices['DOU']) formatSlices['DOU'] = formatSlices['New'];
			if (!formatSlices['DUU']) formatSlices['DUU'] = formatSlices['New'];
		}
		const itemList = Object.keys(Dex.data.Items);
		itemList.sort();
		const greatItems = [['header', "Popular items"]];
		const goodItems = [['header', "Items"]];
		const specificItems = [['header', "Pok\u00e9mon-specific items"]];
		const poorItems = [['header', "Usually useless items"]];
		const badItems = [['header', "Useless items"]];
		const unreleasedItems = [];
		if (genNum === 6) unreleasedItems.push(['header', "Unreleased"]);
		for (const id of itemList) {
			const item = Dex.mod(gen).items.get(id);
			if (item.gen > genNum) { continue; }
			if (item.isNonstandard && !isMetBattle) {
				if (isNatDex) {
					let curItem = item;
					let curGen = genNum;
					while (curItem.isNonstandard && curGen >= 7) {
						try { curItem = Dex.forGen(curGen).items.get(item.id); } 
						catch (e) { break; }
						curGen--;
					}
					if (curItem.isNonstandard) continue;
				} else if (genNum !== 2) { continue; }
			}
			if (isMetBattle) {
				const banlist = Dex.formats.getRuleTable(Dex.formats.get(gen + 'metronomebattle'));
				if (banlist.isBanned('item:' + item.id)) continue;
			}
			switch (id) { // mainstays
			case 'choiceband':
			case 'choicespecs':
			case 'eviolite':
				greatItems.push(id);
				break;
			// great everywhere but metronome
			case 'leftovers':
			case 'lifeorb':
			case 'choicescarf':
			case 'assaultvest':
			case 'focussash':
			case 'powerherb':
			case 'rockyhelmet':
				if (!isMetBattle) greatItems.push(id);
				else goodItems.push(id);
				break;
			// just singles
			case 'airballoon':
			case 'loadeddice':
			case 'heavydutyboots':
			case 'expertbelt':
			case 'salacberry':
				if (isDoubles || isMetBattle) goodItems.push(id);
				else greatItems.push(id);
				break;
			// just doubles
			case 'safetygoggles':
			case 'ejectbutton':
			case 'ejectpack':
				if (isDoubles) greatItems.push(id);
				else goodItems.push(id);
				break;
			// doubles + metronome
			case 'covertcloak':
			case 'clearamulet':
			case 'weaknesspolicy':
				if (isDoubles || isMetBattle) greatItems.push(id);
				else goodItems.push(id);
				break;
			// metronome only
			case 'mirrorherb':
				if (isMetBattle) greatItems.push(id);
				else goodItems.push(id);
				break;
			// generation specific
			case 'mentalherb':
				if (isMetBattle) goodItems.push(id);
				else if (genNum > 4) greatItems.push(id);
				else poorItems.push(id);
				break;
			case 'lumberry':
				if (genNum === 2 || genNum > 6) goodItems.push(id);
				else greatItems.push(id);
				break;
			case 'sitrusberry':
				if (genNum > 3 && (genNum < 7 || isDoubles)) greatItems.push(id);
				else if (genNum > 6) goodItems.push(id);
				else poorItems.push(id);
				break;
			case 'aguavberry':
			case 'figyberry':
			case 'iapapaberry':
			case 'magoberry':
			case 'wikiberry':
				if (genNum === 7) greatItems.push(id);
				else if (genNum >= 8) goodItems.push(id);
				else poorItems.push(id);
				break;
			case 'berryjuice':
				if (genNum === 2) poorItems.push(id);
				else goodItems.push(id);
				break;
			case 'dragonfang':
				if (genNum === 2) badItems.push(id);
				else goodItems.push(id);
				break;
			case 'dragonscale':
				if (genNum === 2) goodItems.push(id);
				else badItems.push(id);
				break;
			case 'mail':
				if (genNum >= 6) unreleasedItems.push(id);
				else goodItems.push(id);
				break;
			// Legendaries
			case 'adamantorb':
			case 'griseousorb':
			case 'lustrousorb':
			case 'blueorb':
			case 'redorb':
			case 'souldew':
			// falls through
			// Other
			case 'leek':
			case 'stick':
			case 'thickclub':
			case 'lightball':
			case 'luckypunch':
			case 'quickpowder':
			case 'metalpowder':
			case 'deepseascale':
			case 'deepseatooth':
				specificItems.push(id);
				break;
			// Fling-only
			case 'rarebone':
			case 'belueberry':
			case 'blukberry':
			case 'cornnberry':
			case 'durinberry':
			case 'hondewberry':
			case 'magostberry':
			case 'nanabberry':
			case 'nomelberry':
			case 'pamtreberry':
			case 'pinapberry':
			case 'pomegberry':
			case 'qualotberry':
			case 'rabutaberry':
			case 'tamatoberry':
			case 'watmelberry':
			case 'wepearberry':
			case 'energypowder':
			case 'electirizer':
			case 'oldamber':
			case 'dubiousdisc':
			case 'magmarizer':
			case 'ovalstone':
			case 'sachet':
			case 'upgrade':
			case 'whippeddream':
			case 'bottlecap':
			case 'goldbottlecap':
			case 'galaricacuff':
			case 'chippedpot':
			case 'crackedpot':
			case 'galaricawreath':
			case 'auspiciousarmor':
			case 'maliciousarmor':
			case 'masterpieceteacup':
			case 'unremarkableteacup':
			case 'bignugget':
				badItems.push(id);
				break;
			// outclassed items
			case 'aspearberry':
			case 'cheriberry':
			case 'destinyknot':
			case 'enigmaberry':
			case 'ironball':
			case 'machobrace':
			case 'pechaberry':
			case 'persimberry':
			case 'poweranklet':
			case 'powerband':
			case 'powerbelt':
			case 'powerbracer':
			case 'powerlens':
			case 'powerweight':
			case 'rawstberry':
			case 'ringtarget':
			case 'focusband':
				poorItems.push(id);
				break;
			default:
				if (
					item.name.endsWith(" Ball") || item.name.endsWith(" Fossil") || item.name.startsWith("Fossilized ") ||
					item.name.endsWith(" Sweet") || item.name.endsWith(" Apple")
				) { badItems.push(id); } 
				else if (item.name.startsWith("TR")) { badItems.push(id); } 
				else if (item.name.endsWith(" Gem") && item.name !== "Normal Gem") {
					if (genNum >= 6) { unreleasedItems.push(id); } 
					else { goodItems.push(id); }
				} 
				else if (item.name.endsWith(" Drive")) { specificItems.push(id); } 
				else if (item.name.endsWith(" Memory")) { specificItems.push(id); } 
				else if (item.name.startsWith("Rusted")) { specificItems.push(id); } 
				else if (item.itemUser) { specificItems.push(id); } 
				else if (item.megaStone) { specificItems.push(id); }
				else { goodItems.push(id); }
			}
		}
		items.push(...greatItems);
		items.push(...goodItems);
		items.push(...specificItems);
		items.push(...poorItems);
		items.push(...badItems);
		items.push(...unreleasedItems);
	}
	//region Learnset table
	const gen3HMs = new Set(['cut', 'fly', 'surf', 'strength', 'flash', 'rocksmash', 'waterfall', 'dive']);
	const gen4HMs = new Set(['cut', 'fly', 'surf', 'strength', 'rocksmash', 'waterfall', 'rockclimb']);
	const learnsets = {};
	BattleTeambuilderTable.learnsets = learnsets;
	for (const id in Dex.data.Learnsets) {
		const learnset = Dex.data.Learnsets[id].learnset;
		if (!learnset) continue;
		learnsets[id] = {};
		for (const moveid in learnset) {
			const gens = learnset[moveid].map(x => Number(x[0]));
			const minGen = Math.min(...gens);
			learnsets[id][moveid] = '0123456789'.slice(minGen); 
			if (gens.indexOf(6) >= 0) learnsets[id][moveid] += 'p';
			if (gens.indexOf(9) >= 0 && learnset[moveid].some(x => x[0] === '9' && x !== '9V')) { learnsets[id][moveid] += 'a'; }
			if (gens.indexOf(9) >= 0 && learnset[moveid].some(x => x === '9E')) learnsets[id][moveid] += 'e';
		}
	}
	// Create nested structure for mod learnsets
	BattleTeambuilderTable['gen9indigostarstorm'] = {};
	BattleTeambuilderTable['gen9indigostarstorm'].learnsets = {};
	console.log('Building tier table for gen9indigostarstorm...');
	const islDex = Dex;
	const rawFormatsData = Dex.data.FormatsData || {};
	// The ONLY regs we want the teambuilder to slice by
	const regs = ['Reg α','Reg Δ','Reg ι','Reg β','Reg ζ','Reg γ','Reg Θ','Reg ε','Reg λ','Reg ψ','Reg ν','Reg φ'];
	const buckets = Object.fromEntries(regs.map(r => [r, []]));
	// Put each species into exactly ONE reg bucket based on FormatsData.tier,
	// falling back to the base species' tier for formes that inherit rather than override it.
	for (const id in Dex.data.Pokedex) {
		const sp = islDex.species.get(id);
		if (!sp || !sp.exists) continue;
		// Avoid MissingNo sprite (0.png spam)
		if (sp.num === 0) continue;
		// Hard-hide categories you never want showing in ISL builder lists
		if (sp.isNonstandard === 'Past' || sp.isNonstandard === 'Gigantamax' || sp.isNonstandard === 'CAP') continue;
		const baseId = toID(sp.baseSpecies);
		const tier = rawFormatsData[id]?.tier || (baseId !== id ? rawFormatsData[baseId]?.tier : undefined);
		if (!tier || typeof tier !== 'string') continue;
		// Ignore smogon tiers and only accept isl tiers
		if (!(tier in buckets)) continue;
		buckets[tier].push(id);
	}
	// Optional: stable ordering by dex number
	for (const r of regs) {
		buckets[r].sort((a, b) => {
			const na = islDex.species.get(a).num || 99999;
			const nb = islDex.species.get(b).num || 99999;
			return na - nb;
		});
	}
	// Build tiers + slices (vanilla-style)
	const islTiers = [];
	const islFormatSlices = {};
	const islOverrideTier = {};
	for (const r of regs) {
		islFormatSlices[r] = islTiers.length;
		islTiers.push(['header', r]);
		for (const pid of buckets[r]) {
			islTiers.push(pid);            // string entry OK (client converts to ['pokemon', ...])
			islOverrideTier[pid] = r;
		}
	}
	BattleTeambuilderTable['gen9indigostarstorm'].tiers = islTiers;
	BattleTeambuilderTable['gen9indigostarstorm'].overrideTier = islOverrideTier;
	BattleTeambuilderTable['gen9indigostarstorm'].formatSlices = islFormatSlices;
	// Build item list for gen9indigostarstorm from the mod Dex (separate from vanilla)
	console.log('Building item list for gen9indigostarstorm...');
	{
		const islDex = Dex;
		const itemIDs = Object.keys(Dex.data.Items);
		itemIDs.sort();
		const greatItems = [['header', "Popular items"]];
		const goodItems = [['header', "Items"]];
		const specificItems = [['header', "Pok\u00e9mon-specific items"]];
		const poorItems = [['header', "Usually useless items"]];
		const badItems = [['header', "Useless items"]];
		const unreleasedItems = [];
		for (const id of itemIDs) {
			const item = islDex.items.get(id);
			if (!item || !item.exists) continue;
			if (item.isNonstandard) {
				unreleasedItems.push(id);
				continue;
			}
			// same buckets as PS, simplified
			switch (id) {
			case 'choiceband':
			case 'choicespecs':
			case 'eviolite':
			case 'leftovers':
			case 'lifeorb':
			case 'choicescarf':
			case 'assaultvest':
			case 'focussash':
			case 'powerherb':
			case 'rockyhelmet':
			case 'covertcloak':
			case 'clearamulet':
			case 'weaknesspolicy':
			case 'heavydutyboots':
			case 'loadeddice':
				greatItems.push(id);
				break;
			default:
				if (item.megaStone || item.itemUser || item.zMove || item.onPlate || item.onDrive || item.onMemory) { specificItems.push(id); } 
				else { goodItems.push(id); }
			}
		}
		const islItems = [];
		islItems.push(...greatItems, ...goodItems, ...specificItems, ...poorItems, ...badItems, ...unreleasedItems);
		BattleTeambuilderTable['gen9indigostarstorm'].items = islItems;
		console.log('Built', islItems.length, 'item entries for gen9indigostarstorm');
	}
	console.log(`Built ${islTiers.length} tier entries for gen9indigostarstorm`);
	// Build gen9indigostarstorm learnsets from the RAW mod Learnsets table (file-backed).
	// Do NOT copy vanilla learnsets first; removals must take effect.
	try {
		console.log('DEBUG: Building gen9indigostarstorm.learnsets from islDex.data.Learnsets');
		BattleTeambuilderTable['gen9indigostarstorm'].learnsets = {};
		const islLearnsetsTable = (islDex.data && islDex.data.Learnsets) ? islDex.data.Learnsets : {};
		console.log('DEBUG: isl Learnsets keys:', Object.keys(islLearnsetsTable).length);
		for (const id in islLearnsetsTable) {
			const entry = islLearnsetsTable[id];
			const learnset = entry && entry.learnset;
			if (!learnset) continue;
			const out = {};
			for (const moveid in learnset) {
				const sources = learnset[moveid];
				if (!sources || !sources.length) continue;
				// sources look like: ["9L1","9M","9E", ...] (or sometimes arrays; normalize defensively)
				const src = (Array.isArray(sources) ? sources : [sources])
					.map(x => Array.isArray(x) ? x[0] : x)
					.filter(x => typeof x === 'string');
				const gens = src.map(s => Number(s.charAt(0))).filter(n => !isNaN(n));
				if (!gens.length) continue;
				const minGen = Math.min(...gens);
				let packed = '0123456789'.slice(minGen);
				// keep behavior consistent with your base learnset packing
				if (gens.includes(6)) packed += 'p';
				if (gens.includes(9) && src.some(s => s.charAt(0) === '9' && s !== '9V')) packed += 'a';
				if (gens.includes(9) && src.includes('9E')) packed += 'e';
				out[moveid] = packed;
			}
			BattleTeambuilderTable['gen9indigostarstorm'].learnsets[id] = out;
		}
		console.log('DEBUG: gen9indigostarstorm.learnsets species count:',
			Object.keys(BattleTeambuilderTable['gen9indigostarstorm'].learnsets).length
		);
		console.log('DEBUG: has poltchageistartisan?',
			('poltchageistartisan' in BattleTeambuilderTable['gen9indigostarstorm'].learnsets),
			'move count:',
			Object.keys(BattleTeambuilderTable['gen9indigostarstorm'].learnsets.poltchageistartisan || {}).length
		);
	} catch (e) { console.log('Note: Could not build mod learnsets from islDex.data.Learnsets:', e && e.message ? e.message : e); }
		{ // Infusible moves
			BattleTeambuilderTable.infusibleMoves = Object.keys(Dex.data.Moves)
				.filter(id => Dex.data.Moves[id] && Dex.data.Moves[id].flags && Dex.data.Moves[id].flags.infusible)
				.sort();
			console.log(`Built ${BattleTeambuilderTable.infusibleMoves.length} infusible move entries`);
		}
		buf += `exports.BattleTeambuilderTable = JSON.parse('${JSON.stringify(BattleTeambuilderTable).replace(/['\\]/g, "\\$&")}');\n\n`;
		fs.writeFileSync('play.pokemonshowdown.com/data/teambuilder-tables.js', buf);
	}
	console.log("DONE");


	//region Build pokedex.js
	process.stdout.write("Building `data/pokedex.js` (base) + mod overlay... "); {
		// BASE (VANILLA) POKEDEX
		const serverPokedexModule = requireServer('dist/data/pokedex.js');
		const basePokedex = pickExport(serverPokedexModule, ['BattlePokedex', 'Pokedex', 'default']);
		if (!basePokedex) throw new Error('Server dist/data/pokedex.js did not export Pokedex/BattlePokedex');
		const Pokedex = cloneObjTable(basePokedex);
		// Preserve the client behavior: merge tiers/nonstandard from base FormatsData
		// (your client expects tier/isNonstandard/unreleasedHidden on BattlePokedex entries)
		for (const id in Pokedex) {
			const entry = Pokedex[id];
			if (Dex.data.FormatsData[id]) {
				const fd = Dex.data.FormatsData[id];
				if (fd.tier) entry.tier = fd.tier;
				if (fd.isNonstandard) entry.isNonstandard = fd.isNonstandard;
				if (fd.unreleasedHidden) entry.unreleasedHidden = fd.unreleasedHidden;
			}
		}
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'pokedex.js'), 'BattlePokedex', Pokedex);
		fs.writeFileSync(path.join(CLIENT_DATA_DIR, 'pokedex.json'), JSON.stringify(Pokedex));
	}
	console.log("DONE");


	//region Build moves.js
	{
		console.log('Building `data/moves.js` (base) + mod overlay...');
		// BASE MOVES (VANILLA)
		const baseMovesTable = {};
		for (const move of Dex.moves.all()) {
			// clone to avoid read-only issues later
			baseMovesTable[move.id] = {...move};
		}
		// ensure text exists (desc/shortDesc) from Dex
		for (const id in baseMovesTable) {
			const m = Dex.moves.get(id);
			if (m?.desc && !baseMovesTable[id].desc) baseMovesTable[id].desc = m.desc;
			if (m?.shortDesc && !baseMovesTable[id].shortDesc) baseMovesTable[id].shortDesc = m.shortDesc;
		}
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'moves.js'), 'BattleMovedex', baseMovesTable);
		fs.writeFileSync(path.join(CLIENT_DATA_DIR, 'moves.json'), JSON.stringify(baseMovesTable));
		console.log('DONE building moves.js');
	}



	//region Build items.js
	{
		console.log('Building `data/items.js` (base) + mod overlay...');
		// BASE ITEMS (VANILLA)
		const Items = cloneObjTable(requireServer('dist/data/items.js').Items);
		for (const id in Items) {
			const it = Dex.items.get(id);
			if (it?.desc && !Items[id].desc) Items[id].desc = it.desc;
			if (it?.shortDesc && !Items[id].shortDesc) Items[id].shortDesc = it.shortDesc;
		}
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'items.js'), 'BattleItems', Items);
	}


	//region Build abilities.js
	{
		console.log('Building `data/abilities.js` (base) + mod overlay...');
		// BASE ABILITIES (VANILLA)
		const Abilities = cloneObjTable(requireServer('dist/data/abilities.js').Abilities);
		for (const id in Abilities) {
			const a = Dex.abilities.get(id);
			if (a?.desc && !Abilities[id].desc) Abilities[id].desc = a.desc;
			if (a?.shortDesc && !Abilities[id].shortDesc) Abilities[id].shortDesc = a.shortDesc;
		}
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'abilities.js'), 'BattleAbilities', Abilities);
	}


	//region Build typechart.js
	{
		console.log('Building `data/typechart.js` from server output...');
		const serverTypechartModule = requireServer('dist/data/typechart.js');
		const TypeChart = pickExport(serverTypechartModule, ['TypeChart', 'BattleTypeChart', 'default']);
		if (!TypeChart || typeof TypeChart !== 'object') { throw new Error('Server dist/data/typechart.js did not export TypeChart'); }
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'typechart.js'), 'BattleTypeChart', TypeChart);
		console.log('DONE building typechart.js');
	}


	//region Build aliases.js
	{
		console.log('Building `data/aliases.js` from server output...');
		const serverAliasesModule = requireServer('dist/data/aliases.js');
		const Aliases = pickExport(serverAliasesModule, ['Aliases', 'BattleAliases', 'default']);
		if (!Aliases || typeof Aliases !== 'object') { throw new Error('Server dist/data/aliases.js did not export Aliases'); }
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'aliases.js'), 'BattleAliases', Aliases);
		console.log('DONE building aliases.js');
	}


	//region Build formats-data.js
	{
		console.log('Building `data/formats-data.js` from server output...');
		const serverFDModule = requireServer('dist/data/formats-data.js');
		const FormatsData = pickExport(serverFDModule, ['BattleFormatsData', 'FormatsData', 'default']);
		if (!FormatsData || typeof FormatsData !== 'object') { throw new Error('Server dist/data/formats-data.js did not export FormatsData/BattleFormatsData'); }
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'formats-data.js'), 'BattleFormatsData', FormatsData);
		fs.writeFileSync(path.join(CLIENT_DATA_DIR, 'formats-data.json'), JSON.stringify(FormatsData));
		console.log(`DONE building formats-data.js (${Object.keys(FormatsData).length} entries)`);
	}


	//region Build formats.js
	{
		console.log('Building `data/formats.js` from server output...');
		const serverFormatsModule = requireServer('dist/config/formats.js');
		const Formats = pickExport(serverFormatsModule, ['Formats', 'default']);
		if (!Formats || typeof Formats !== 'object') { throw new Error('Server dist/config/formats.js did not export Formats'); }
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'formats.js'), 'Formats', Formats);
		fs.writeFileSync(path.join(CLIENT_DATA_DIR, 'formats.json'), JSON.stringify(Formats));
		// helpful smoke check: look for your mod format id/name
		const asString = JSON.stringify(Formats);
		console.log('formats.js contains "indigostarstorm"?', asString.includes('indigostarstorm'));
		console.log(`DONE building formats.js (${Array.isArray(Formats) ? Formats.length : Object.keys(Formats).length} entries)`);
	}


	//region Build learnsets.js
	{
		console.log('Building `data/learnsets.js` (base) + mod overlay...');
		const serverLearnsetsModule = requireServer('dist/data/learnsets.js');
		const baseLearnsets = pickExport(serverLearnsetsModule, ['BattleLearnsets', 'Learnsets', 'default']);
		if (!baseLearnsets) throw new Error('Server dist/data/learnsets.js did not export Learnsets/BattleLearnsets');
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'learnsets.js'), 'BattleLearnsets', baseLearnsets);
		fs.writeFileSync(path.join(CLIENT_DATA_DIR, 'learnsets.json'), JSON.stringify(baseLearnsets));
	}


	//region Build flags.js
	{
		console.log('Building `data/flags.js` from real move flags + species tags...');
		const flagsTable = {};
		for (const id in Dex.data.Moves) {
			const flags = Dex.data.Moves[id].flags;
			if (!flags) continue;
			for (const flagId in flags) { flagsTable[flagId] = 1; }
		}
		for (const id in Dex.data.Pokedex) {
			const tags = Dex.data.Pokedex[id].tags;
			if (!tags) continue;
			for (const tag of tags) { flagsTable[toID(tag)] = 1; }
		}
		writeBattleExport(path.join(CLIENT_DATA_DIR, 'flags.js'), 'BattleFlags', flagsTable);
		console.log(`DONE building flags.js (${Object.keys(flagsTable).length} entries)`);
	}

	
	//region Build text-desc.js (DO NOT overwrite battle text.js)
	{
		const textDataDefault = Dex.loadTextData();
		function buildTextTable(textData) {
			const Text = {};
			function assignData(id, entry) {
				const out = Text[id] || (Text[id] = {});
				for (const key in entry) {
					if (key === 'name') continue;
					out[key] = entry[key];
				}
			}
			for (const id in textData.Moves) assignData(id, textData.Moves[id]);
			for (const id in textData.Abilities) assignData(id, textData.Abilities[id]);
			for (const id in textData.Items) assignData(id, textData.Items[id]);
			return Text;
		}
		const out = { default: buildTextTable(textDataDefault.Default), };
		fs.writeFileSync(
			'play.pokemonshowdown.com/data/text-desc.js',
			'exports.BattleTextDesc = ' + es3stringify(out) + ';'
		);
	}
	console.log(`DONE. Total build-indexes time: ${((Date.now() - buildStartTime) / 1000).toFixed(1)}s`);